import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeProvider from "@/context/ThemesProvider";
import { cn } from "@/utils";
import Header from "@/components/Header/Header";

const figtree = localFont({
  src: "./fonts/Figtree-Variable.woff2",
  variable: "--font-figtree",
  weight: "400",
});
const lora = localFont({
  src: "./fonts/Lora-Variable.woff2",
  variable: "--font-lora",
  weight: "700",
});
const sourceSans = localFont({
  src: "./fonts/SourceSans3-Variable.woff2",
  variable: "--font-source-sans",
  weight: "400 600",
});

export const metadata: Metadata = {
  // do zmiany na późniejszym etapie projektu
  title: "AK1944",
  description: "Generated by create next app",
  keywords:
    "Armia Krajowa, Dębica, AK Dębica, Szlak Partyzancki, Szlak II Zgrupowania, Szlak Partyzancki II Zgrupowania Armii Krajowej Obwodu Dębica, Deser, Adam Lazarowicz, Środowisko 5 Pułku Strzelców Konnych Armii Krajowej, ŚZŻAK, Światowy Związek Żołnierzy AK, 5 Pułk Strzelców Konnych, 5 psk, AK, powiat dębicki, ziemia dębicka, Maciej Małozięć, weterani AK, kombatanci, Polskie Państwo Podziemne, Dziekania, Braciejowa, Gumniska, biogramy żołnierzy, Gdzie Karpat progi, Dziesiątka w akcji, Wojenne losy uczniów",
  // do zmiany na późniejszym etapie projektu
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" data-lt-installed="true">
      <body
        className={cn(
          figtree.variable,
          lora.variable,
          sourceSans.variable,
          "antialiased",
        )}
      >
        <ThemeProvider>
          <Header />
          <main className="pt-[80px] tablet:pt-[130px] desktop:pt-[120px]">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
