export interface NameDay {
  id: string;
  date: string;
  names: string[];
}

// Funkcja pomocnicza do znajdowania imienin dla danego dnia
export const getNameDaysForDate = (date: string): string[] => {
  const nameDay = nameDaysData.find((item) => item.date === date);
  return nameDay ? nameDay.names : [];
};

// Funkcja pomocnicza do znajdowania imienin dla dzisiejszego dnia
export const getTodaysNameDays = (): string[] => {
  const today = new Date();
  const day = today.getDate().toString().padStart(2, "0");
  const month = (today.getMonth() + 1).toString().padStart(2, "0");
  const dateString = `${day}.${month}`;

  return getNameDaysForDate(dateString);
};

export const nameDaysData: NameDay[] = [
  // STYCZEŃ
  { id: "1", date: "01.01", names: ["Mieczysław", "Wilhelm", "Józef"] },
  { id: "2", date: "02.01", names: ["Makary", "Bazyli", "Grzegorz"] },
  { id: "3", date: "03.01", names: ["Genowefa", "Arleta", "Daniel"] },
  { id: "4", date: "04.01", names: ["Elżbieta", "Eugeniusz", "Grzegorz"] },
  { id: "5", date: "05.01", names: ["Amelia", "Edward", "Hanna"] },
  { id: "6", date: "06.01", names: ["Kacper", "Melchior", "Baltazar"] },
  { id: "7", date: "07.01", names: ["Julian", "Lucjan", "Łucjan"] },
  { id: "8", date: "08.01", names: ["Mścisław", "Seweryn", "Teofil"] },
  { id: "9", date: "09.01", names: ["Marcelina", "Adrian", "Agata"] },
  { id: "10", date: "10.01", names: ["Anna", "Grzegorz", "Jan"] },
  { id: "11", date: "11.01", names: ["Honorata", "Hortensja", "Matylda"] },
  { id: "12", date: "12.01", names: ["Arkadiusz", "Alfred", "Benedykt"] },
  { id: "13", date: "13.01", names: ["Weronika", "Bogumił", "Bogumiła"] },
  { id: "14", date: "14.01", names: ["Feliks", "Helga", "Nina"] },
  { id: "15", date: "15.01", names: ["Aleksander", "Izydor", "Paweł"] },
  { id: "16", date: "16.01", names: ["Otto", "Tycjan", "Włodzimierz"] },
  { id: "17", date: "17.01", names: ["Antoni", "Kamil", "Teodor"] },
  { id: "18", date: "18.01", names: ["Krystyna", "Małgorzata", "Monika"] },
  { id: "19", date: "19.01", names: ["Henryk", "Mariusz", "Andrzej"] },
  { id: "20", date: "20.01", names: ["Sebastian", "Fabian"] },
  { id: "21", date: "21.01", names: ["Agnieszka", "Inez", "Jarosław"] },
  { id: "22", date: "22.01", names: ["Anastazy", "Dominik", "Mateusz"] },
  { id: "23", date: "23.01", names: ["Ildefons", "Bartłomiej", "Filip"] },
  { id: "24", date: "24.01", names: ["Milena", "Ksenia", "Rafał"] },
  { id: "25", date: "25.01", names: ["Miłosz", "Paweł", "Tatiana"] },
  { id: "26", date: "26.01", names: ["Paula", "Tymoteusz", "Wanda"] },
  { id: "27", date: "27.01", names: ["Angela", "Henryk", "Jerzy"] },
  { id: "28", date: "28.01", names: ["Jakub", "Karol", "Piotr"] },
  { id: "29", date: "29.01", names: ["Zdzisław", "Ismena", "Walerian"] },
  { id: "30", date: "30.01", names: ["Maciej", "Martyna", "Bronisław"] },
  { id: "31", date: "31.01", names: ["Jan", "Euzebiusz", "Ksawery"] },

  // LUTY
  { id: "32", date: "01.02", names: ["Brygida", "Emil", "Iga"] },
  { id: "33", date: "02.02", names: ["Filip", "Joanna", "Katarzyna"] },
  { id: "34", date: "03.02", names: ["Oskar", "Błażej", "Hipolit"] },
  { id: "35", date: "04.02", names: ["Andrzej", "Jan", "Mariusz"] },
  { id: "36", date: "05.02", names: ["Agata", "Adelajda", "Jakub"] },
  { id: "37", date: "06.02", names: ["Bohdan", "Dorota", "Ksenia"] },
  { id: "38", date: "07.02", names: ["Romuald", "Ryszard", "Teodor"] },
  { id: "39", date: "08.02", names: ["Gabriela", "Hieronim", "Paweł"] },
  { id: "40", date: "09.02", names: ["Pola", "Apolonia", "Marian"] },
  { id: "41", date: "10.02", names: ["Jacek", "Scholastyka", "Wilhelm"] },
  { id: "42", date: "11.02", names: ["Bernadeta", "Grzegorz", "Maria"] },
  { id: "43", date: "12.02", names: ["Damian", "Ewa", "Aleksy"] },
  { id: "44", date: "13.02", names: ["Katarzyna", "Grzegorz", "Julian"] },
  { id: "45", date: "14.02", names: ["Walenty", "Dagmara", "Konrad"] },
  { id: "46", date: "15.02", names: ["Jowita", "Zygfryd", "Alicja"] },
  { id: "47", date: "16.02", names: ["Daniel", "Danuta", "Szymon"] },
  { id: "48", date: "17.02", names: ["Łukasz", "Bartłomiej", "Franciszek"] },
  { id: "49", date: "18.02", names: ["Albert", "Konstancja", "Szymon"] },
  { id: "50", date: "19.02", names: ["Arnold", "Henryk", "Jerzy"] },
  { id: "51", date: "20.02", names: ["Elżbieta", "Eustachy", "Julia"] },
  { id: "52", date: "21.02", names: ["Henryka", "Eleonora", "Kiejstut"] },
  { id: "53", date: "22.02", names: ["Jakub", "Małgorzata", "Wiktor"] },
  { id: "54", date: "23.02", names: ["Damian", "Izabela", "Łazarz"] },
  { id: "55", date: "24.02", names: ["Bogusz", "Maciej", "Marek"] },
  { id: "56", date: "25.02", names: ["Adam", "Cezary", "Modest"] },
  { id: "57", date: "26.02", names: ["Mirosław", "Aleksander", "Arkadiusz"] },
  { id: "58", date: "27.02", names: ["Gabriel", "Anastazja", "Anna"] },
  { id: "59", date: "28.02", names: ["Hilary", "Józef", "Roman"] },
  { id: "60", date: "29.02", names: ["Roman", "Oswald"] },

  // MARZEC
  { id: "61", date: "01.03", names: ["Albin", "Antoni", "Dawid"] },
  { id: "62", date: "02.03", names: ["Elena", "Halszka", "Helena"] },
  { id: "63", date: "03.03", names: ["Teresa", "Anzelm", "Hieronim"] },
  { id: "64", date: "04.03", names: ["Kazimiera", "Kazimierz", "Arkadiusz"] },
  { id: "65", date: "05.03", names: ["Adrian", "Fryderyk", "Oliwia"] },
  { id: "66", date: "06.03", names: ["Jordan", "Róża", "Wiktor"] },
  { id: "67", date: "07.03", names: ["Tomasz", "Felicyta", "Paweł"] },
  { id: "68", date: "08.03", names: ["Beata", "Stefan", "Szymon"] },
  { id: "69", date: "09.03", names: ["Dominik", "Franciszka", "Katarzyna"] },
  { id: "70", date: "10.03", names: ["Aleksander", "Cyprian", "Marceli"] },
  { id: "71", date: "11.03", names: ["Konstanty", "Teresa", "Balbina"] },
  { id: "72", date: "12.03", names: ["Grzegorz", "Alojzy", "Bernard"] },
  { id: "73", date: "13.03", names: ["Krystyna", "Bożena", "Marek"] },
  { id: "74", date: "14.03", names: ["Ewa", "Jakub", "Matylda"] },
  { id: "75", date: "15.03", names: ["Klemens", "Krzysztof", "Longin"] },
  { id: "76", date: "16.03", names: ["Henryka", "Henryk", "Hilary"] },
  { id: "77", date: "17.03", names: ["Gertruda", "Patrycjusz", "Patryk"] },
  { id: "78", date: "18.03", names: ["Anzelm", "Cyryl", "Edward"] },
  { id: "79", date: "19.03", names: ["Józef", "Bogdan", "Marek"] },
  { id: "80", date: "20.03", names: ["Klaudia", "Aleksandra", "Patrycja"] },
  { id: "81", date: "21.03", names: ["Benedykt", "Marzanna", "Lubomir"] },
  { id: "82", date: "22.03", names: ["Bazyli", "Bogusław", "Katarzyna"] },
  { id: "83", date: "23.03", names: ["Oktawian", "Pelagia", "Zbysław"] },
  { id: "84", date: "24.03", names: ["Marek", "Gabriel", "Katarzyna"] },
  { id: "85", date: "25.03", names: ["Ireneusz", "Małgorzata", "Maria"] },
  { id: "86", date: "26.03", names: ["Emanuel", "Emanuela", "Larysa"] },
  { id: "87", date: "27.03", names: ["Lidia", "Ernest", "Jan"] },
  { id: "88", date: "28.03", names: ["Aniela", "Joanna", "Renata"] },
  { id: "89", date: "29.03", names: ["Marek", "Wiktoria", "Wiktoryn"] },
  { id: "90", date: "30.03", names: ["Amelia", "Dobromir", "Leonard"] },
  { id: "91", date: "31.03", names: ["Kornelia", "Balbina", "Beniamin"] },

  // KWIECIEŃ
  { id: "92", date: "01.04", names: ["Grażyna", "Katarzyna", "Zbigniew"] },
  { id: "93", date: "02.04", names: ["Franciszek", "Maria", "Urban"] },
  { id: "94", date: "03.04", names: ["Ryszard", "Sykstus"] },
  { id: "95", date: "04.04", names: ["Benedykt", "Izydor"] },
  { id: "96", date: "05.04", names: ["Irena", "Wincenty", "Jeremi"] },
  { id: "97", date: "06.04", names: ["Ada", "Adam", "Celestyna"] },
  { id: "98", date: "07.04", names: ["Herman", "Krystian"] },
  { id: "99", date: "08.04", names: ["Dionizy", "January", "Julia"] },
  { id: "100", date: "09.04", names: ["Maja", "Dominik", "Dymitr"] },
  { id: "101", date: "10.04", names: ["Michał", "Daniel", "Henryk"] },
  { id: "102", date: "11.04", names: ["Filip", "Helena", "Leon"] },
  { id: "103", date: "12.04", names: ["Iwan", "Andrzej", "Damian"] },
  { id: "104", date: "13.04", names: ["Przemysław", "Hermenegilda", "Ida"] },
  { id: "105", date: "14.04", names: ["Justyna", "Julianna", "Krzysztof"] },
  { id: "106", date: "15.04", names: ["Anastazja", "Olimpia", "Sylwester"] },
  { id: "107", date: "16.04", names: ["Julia", "Erwina", "Bernadeta"] },
  { id: "108", date: "17.04", names: ["Robert", "Innocenty", "Jakub"] },
  { id: "109", date: "18.04", names: ["Bogusława", "Alicja", "Apoloniusz"] },
  { id: "110", date: "19.04", names: ["Tymon", "Adolf", "Jerzy"] },
  { id: "111", date: "20.04", names: ["Agnieszka", "Jagna", "Amelia"] },
  { id: "112", date: "21.04", names: ["Bartosz", "Konrad", "Aleksandra"] },
  { id: "113", date: "22.04", names: ["Gaja", "Kaja", "Łukasz"] },
  { id: "114", date: "23.04", names: ["Gabriela", "Jerzy", "Wojciech"] },
  { id: "115", date: "24.04", names: ["Grzegorz", "Aleksander", "Aleksy"] },
  { id: "116", date: "25.04", names: ["Jarosław", "Marek"] },
  { id: "117", date: "26.04", names: ["Marzena", "Grzegorz", "Marcelina"] },
  { id: "118", date: "27.04", names: ["Andrzej", "Felicja", "Marcin"] },
  { id: "119", date: "28.04", names: ["Ludwik", "Marek", "Paweł"] },
  { id: "120", date: "29.04", names: ["Bogusław", "Katarzyna", "Robert"] },
  { id: "121", date: "30.04", names: ["Marian", "Bartłomiej", "Jakub"] },

  // MAJ
  { id: "122", date: "01.05", names: ["Jeremiasz", "Jakub", "Józef"] },
  { id: "123", date: "02.05", names: ["Borys", "Zoja", "Zygmunt"] },
  { id: "124", date: "03.05", names: ["Aleksander", "Antonina", "Maria"] },
  { id: "125", date: "04.05", names: ["Florian", "Monika", "Damian"] },
  { id: "126", date: "05.05", names: ["Irena", "Waldemar", "Ireneusz"] },
  { id: "127", date: "06.05", names: ["Judyta", "Filip", "Jan"] },
  { id: "128", date: "07.05", names: ["Benedykt", "Gizela", "Ludmiła"] },
  { id: "129", date: "08.05", names: ["Stanisław", "Stanisława"] },
  { id: "130", date: "09.05", names: ["Karolina", "Grzegorz", "Katarzyna"] },
  { id: "131", date: "10.05", names: ["Antoni", "Wiktoryna", "Samuel"] },
  { id: "132", date: "11.05", names: ["Filip", "Franciszek", "Ignacy"] },
  { id: "133", date: "12.05", names: ["Dominik", "Pankracy", "Teodora"] },
  { id: "134", date: "13.05", names: ["Gloria", "Serwacy", "Agnieszka"] },
  { id: "135", date: "14.05", names: ["Bonifacy", "Maciej", "Stefania"] },
  { id: "136", date: "15.05", names: ["Zofia", "Izydor", "Wera"] },
  { id: "137", date: "16.05", names: ["Adam", "Andrzej", "Szymon"] },
  { id: "138", date: "17.05", names: ["Weronika", "Brunon", "Sławomir"] },
  { id: "139", date: "18.05", names: ["Aleksander", "Aleksandra", "Eryk"] },
  { id: "140", date: "19.05", names: ["Piotr", "Iwo", "Iwona"] },
  { id: "141", date: "20.05", names: ["Wiktoria", "Anastazy", "Bernardyn"] },
  { id: "142", date: "21.05", names: ["Jan", "Krzysztof", "Tymoteusz"] },
  { id: "143", date: "22.05", names: ["Wiesława", "Emil", "Helena"] },
  { id: "144", date: "23.05", names: ["Iwona", "Dezyderiusz", "Emilia"] },
  { id: "145", date: "24.05", names: ["Joanna", "Zuzanna", "Dagmara"] },
  { id: "146", date: "25.05", names: ["Grzegorz", "Magdalena", "Mariusz"] },
  { id: "147", date: "26.05", names: ["Angelika", "Ewelina", "Paulina"] },
  { id: "148", date: "27.05", names: ["Oliwier", "Juliusz", "Magdalena"] },
  { id: "149", date: "28.05", names: ["Wiktor", "Augustyn", "Jaromir"] },
  { id: "150", date: "29.05", names: ["Magdalena", "Urszula", "Maksymilian"] },
  { id: "151", date: "30.05", names: ["Ferdynand", "Żaneta"] },
  { id: "152", date: "31.05", names: ["Kamila", "Aniela", "Petronela"] },

  // CZERWIEC
  { id: "153", date: "01.06", names: ["Jakub", "Konrad", "Magdalena"] },
  { id: "154", date: "02.06", names: ["Marianna", "Erazm", "Piotr"] },
  { id: "155", date: "03.06", names: ["Leszek", "Tamara", "Wawrzyniec"] },
  { id: "156", date: "04.06", names: ["Karol"] },
  { id: "157", date: "05.06", names: ["Bonifacy", "Waleria", "Igor"] },
  { id: "158", date: "06.06", names: ["Dominika", "Norbert", "Paulina"] },
  { id: "159", date: "07.06", names: ["Anna", "Hanna", "Jarosław"] },
  { id: "160", date: "08.06", names: ["Seweryn", "Jadwiga", "Maksym"] },
  { id: "161", date: "09.06", names: ["Anna", "Felicjan", "Pelagia"] },
  { id: "162", date: "10.06", names: ["Bogumił", "Bogumiła", "Edgar"] },
  { id: "163", date: "11.06", names: ["Barnaba", "Teodozja"] },
  { id: "164", date: "12.06", names: ["Janina", "Mieczysław", "Czesław"] },
  { id: "165", date: "13.06", names: ["Antoni", "Gracja", "Grzegorz"] },
  { id: "166", date: "14.06", names: ["Eliza", "Rufin", "Ryszard"] },
  { id: "167", date: "15.06", names: ["Jolanta", "Wit", "Adelajda"] },
  { id: "168", date: "16.06", names: ["Alina", "Aneta", "Justyna"] },
  { id: "169", date: "17.06", names: ["Adolf", "Laura", "Adrianna"] },
  { id: "170", date: "18.06", names: ["Elżbieta", "Leonia", "Marek"] },
  { id: "171", date: "19.06", names: ["Gerwazy", "Julianna", "Protazy"] },
  { id: "172", date: "20.06", names: ["Bogna", "Bożena", "Florentyna"] },
  { id: "173", date: "21.06", names: ["Alicja", "Marta", "Rudolf"] },
  { id: "174", date: "22.06", names: ["Paulina", "Tomasz", "Innocenty"] },
  { id: "175", date: "23.06", names: ["Wanda", "Zenon", "Adrian"] },
  { id: "176", date: "24.06", names: ["Danuta", "Jan", "Janina"] },
  { id: "177", date: "25.06", names: ["Dorota", "Łucja"] },
  { id: "178", date: "26.06", names: ["Dawid", "Jan", "Paweł"] },
  { id: "179", date: "27.06", names: ["Maryla", "Władysław", "Cyryl"] },
  { id: "180", date: "28.06", names: ["Ireneusz", "Adrian", "Józef"] },
  { id: "181", date: "29.06", names: ["Paweł", "Piotr", "Beata"] },
  { id: "182", date: "30.06", names: ["Emilia", "Lucyna", "Bazyli"] },

  // LIPIEC
  { id: "183", date: "01.07", names: ["Halina", "Bogusław", "Karolina"] },
  { id: "184", date: "02.07", names: ["Jagoda", "Urban", "Mia"] },
  { id: "185", date: "03.07", names: ["Anatol", "Jacek", "Tomasz"] },
  { id: "186", date: "04.07", names: ["Elżbieta", "Jacek", "Józef"] },
  { id: "187", date: "05.07", names: ["Antoni", "Bartłomiej", "Filomena"] },
  { id: "188", date: "06.07", names: ["Dominika", "Dominik", "Teresa"] },
  { id: "189", date: "07.07", names: ["Estera", "Metody"] },
  { id: "190", date: "08.07", names: ["Adrian", "Edgar", "Elżbieta"] },
  { id: "191", date: "09.07", names: ["Sylwia", "Adrian", "Barbara"] },
  { id: "192", date: "10.07", names: ["Daniel", "Filip", "Aniela"] },
  { id: "193", date: "11.07", names: ["Cyprian", "Olga", "Benedykt"] },
  { id: "194", date: "12.07", names: ["Andrzej", "Brunon", "Bruno"] },
  { id: "195", date: "13.07", names: ["Sara", "Ernest", "Eugeniusz"] },
  { id: "196", date: "14.07", names: ["Damian", "Bohdan", "Donald"] },
  { id: "197", date: "15.07", names: ["Henryk", "Włodzimierz", "Anna"] },
  { id: "198", date: "16.07", names: ["Elwira", "Maria", "Stefan"] },
  { id: "199", date: "17.07", names: ["Aneta", "Bogdan", "Aleksy"] },
  { id: "200", date: "18.07", names: ["Arnold", "Kamil", "Karolina"] },
  { id: "201", date: "19.07", names: ["Marcin", "Włodzisław"] },
  { id: "202", date: "20.07", names: ["Czesław", "Hieronim", "Małgorzata"] },
  { id: "203", date: "21.07", names: ["Daniel", "Andrzej", "Julia"] },
  { id: "204", date: "22.07", names: ["Magdalena", "Józef", "Maria"] },
  { id: "205", date: "23.07", names: ["Apolinary", "Bogna", "Brygida"] },
  { id: "206", date: "24.07", names: ["Kinga", "Krystyna", "Kunegunda"] },
  { id: "207", date: "25.07", names: ["Jakub", "Krzysztof", "Dariusz"] },
  { id: "208", date: "26.07", names: ["Anna", "Hanna", "Anita"] },
  { id: "209", date: "27.07", names: ["Natalia", "Natasza", "Adrian"] },
  { id: "210", date: "28.07", names: ["Aida", "Wiktor", "Marcela"] },
  { id: "211", date: "29.07", names: ["Marta", "Olaf", "Teodor"] },
  { id: "212", date: "30.07", names: ["Julita", "Ludmiła", "Maryna"] },
  { id: "213", date: "31.07", names: ["Ignacy", "Adam", "Helena"] },

  // SIERPIEŃ
  { id: "214", date: "01.08", names: ["Justyna", "Nadia", "Piotr"] },
  { id: "215", date: "02.08", names: ["Karina", "Gustaw"] },
  { id: "216", date: "03.08", names: ["Augustyn", "Kira", "Lidia"] },
  { id: "217", date: "04.08", names: ["Jan"] },
  { id: "218", date: "05.08", names: ["Maria", "Oswald", "Kasjan"] },
  { id: "219", date: "06.08", names: ["Jakub", "Sława"] },
  { id: "220", date: "07.08", names: ["Kajetan", "Albert", "Dorota"] },
  { id: "221", date: "08.08", names: ["Dominik", "Emilian"] },
  { id: "222", date: "09.08", names: ["Roman", "Edyta", "Romuald"] },
  { id: "223", date: "10.08", names: ["Amadeusz", "Bogdan", "Wawrzyniec"] },
  { id: "224", date: "11.08", names: ["Zuzanna", "Włodzimierz", "Herman"] },
  { id: "225", date: "12.08", names: ["Klara", "Julian", "Lech"] },
  { id: "226", date: "13.08", names: ["Kasjan", "Diana", "Helena"] },
  { id: "227", date: "14.08", names: ["Alfred", "Elżbieta", "Euzebiusz"] },
  { id: "228", date: "15.08", names: ["Maria", "Napoleon", "Nikodem"] },
  { id: "229", date: "16.08", names: ["Joachim", "Roch", "Stefan"] },
  { id: "230", date: "17.08", names: ["Anita", "Jacek", "Julianna"] },
  { id: "231", date: "18.08", names: ["Ilona", "Bronisław", "Eryk"] },
  { id: "232", date: "19.08", names: ["Julian", "Bolesław", "Juliusz"] },
  { id: "233", date: "20.08", names: ["Bernard", "Krzysztof", "Sobiesław"] },
  { id: "234", date: "21.08", names: ["Franciszek", "Joanna", "Kazimiera"] },
  { id: "235", date: "22.08", names: ["Cezary", "Hipolit", "Maria"] },
  { id: "236", date: "23.08", names: ["Apolinary", "Filip", "Petra"] },
  { id: "237", date: "24.08", names: ["Bartłomiej", "Bartosz", "Anita"] },
  { id: "238", date: "25.08", names: ["Grzegorz", "Ludwik", "Luiza"] },
  { id: "239", date: "26.08", names: ["Maksym", "Maria", "Natalia"] },
  { id: "240", date: "27.08", names: ["Józef", "Małgorzata", "Monika"] },
  { id: "241", date: "28.08", names: ["Patrycja", "Augustyn", "Jadwiga"] },
  { id: "242", date: "29.08", names: ["Sabina", "Beata", "Flora"] },
  { id: "243", date: "30.08", names: ["Małgorzata", "Miron", "Rebeka"] },
  { id: "244", date: "31.08", names: ["Bohdan", "Izabela", "Paulina"] },

  // WRZESIEŃ
  { id: "245", date: "01.09", names: ["Bronisław", "Bronisława", "Idzi"] },
  { id: "246", date: "02.09", names: ["Julian", "Stefan", "Bohdan"] },
  { id: "247", date: "03.09", names: ["Izabela", "Antoni", "Bartłomiej"] },
  { id: "248", date: "04.09", names: ["Ida", "Katarzyna", "Liliana"] },
  { id: "249", date: "05.09", names: ["Dorota", "Wawrzyniec", "Urban"] },
  { id: "250", date: "06.09", names: ["Beata", "Eugeniusz", "Ewa"] },
  { id: "251", date: "07.09", names: ["Regina", "Ryszard"] },
  { id: "252", date: "08.09", names: ["Adrianna", "Maria", "Miriam"] },
  { id: "253", date: "09.09", names: ["Grażyna", "Piotr", "Sergiusz"] },
  { id: "254", date: "10.09", names: ["Łukasz", "Aldona", "Mikołaj"] },
  { id: "255", date: "11.09", names: ["Dagna", "Feliks", "Jacek"] },
  { id: "256", date: "12.09", names: ["Gwidon", "Maja", "Sylwin"] },
  { id: "257", date: "13.09", names: ["Aureliusz", "Apolinary", "Eugenia"] },
  { id: "258", date: "14.09", names: ["Bernard", "Szymon"] },
  { id: "259", date: "15.09", names: ["Albin", "Kamil", "Katarzyna"] },
  { id: "260", date: "16.09", names: ["Edyta", "Kamila", "Cyprian"] },
  { id: "261", date: "17.09", names: ["Franciszek", "Dawid", "Justyna"] },
  { id: "262", date: "18.09", names: ["Irena", "Józef", "Stanisław"] },
  { id: "263", date: "19.09", names: ["January", "Konstancja", "Marta"] },
  { id: "264", date: "20.09", names: ["Agnieszka", "Barbara", "Eustachy"] },
  { id: "265", date: "21.09", names: ["Jonasz", "Mateusz", "Marek"] },
  { id: "266", date: "22.09", names: ["Tomasz", "Daria", "Maurycy"] },
  { id: "267", date: "23.09", names: ["Bogusław", "Elżbieta", "Krzysztof"] },
  { id: "268", date: "24.09", names: ["Gerard", "Herman", "Jaromir"] },
  { id: "269", date: "25.09", names: ["Aurelia", "Franciszek", "Kamil"] },
  { id: "270", date: "26.09", names: ["Teresa", "Justyna", "Kacper"] },
  { id: "271", date: "27.09", names: ["Damian", "Kosma", "Wincenty"] },
  { id: "272", date: "28.09", names: ["Marek", "Wacław", "Bernardyn"] },
  { id: "273", date: "29.09", names: ["Michał", "Rafał", "Dariusz"] },
  { id: "274", date: "30.09", names: ["Sonia", "Felicja", "Grzegorz"] },

  // PAŹDZIERNIK
  { id: "275", date: "01.10", names: ["Danuta", "Igor", "Julia"] },
  { id: "276", date: "02.10", names: ["Aleksandra", "Teofil"] },
  { id: "277", date: "03.10", names: ["Teresa", "Dionizy", "Gerard"] },
  { id: "278", date: "04.10", names: ["Franciszek", "Konrad", "Alfred"] },
  { id: "279", date: "05.10", names: ["Faustyna", "Apolinary", "Bartłomiej"] },
  { id: "280", date: "06.10", names: ["Artur", "Bronisław", "Monika"] },
  { id: "281", date: "07.10", names: ["Justyna", "Marek", "Mateusz"] },
  { id: "282", date: "08.10", names: ["Marcin", "Pelagia", "Dymitr"] },
  { id: "283", date: "09.10", names: ["Arnold", "Bogdan", "Jakub"] },
  { id: "284", date: "10.10", names: ["Daniel", "Franciszek", "Paulina"] },
  { id: "285", date: "11.10", names: ["Aldona", "Marian", "Emanuel"] },
  { id: "286", date: "12.10", names: ["Maksymilian", "Marcin", "Serafin"] },
  { id: "287", date: "13.10", names: ["Edward", "Magdalena", "Wacław"] },
  { id: "288", date: "14.10", names: ["Bernard", "Dominik", "Kalikst"] },
  { id: "289", date: "15.10", names: ["Jadwiga", "Teresa", "Brunon"] },
  { id: "290", date: "16.10", names: ["Emil", "Florentyna", "Gaweł"] },
  { id: "291", date: "17.10", names: ["Wiktor", "Lucyna", "Małgorzata"] },
  { id: "292", date: "18.10", names: ["Łukasz", "Julian"] },
  { id: "293", date: "19.10", names: ["Piotr", "Kleopatra", "Paweł"] },
  { id: "294", date: "20.10", names: ["Irena", "Jerzy", "Witalis"] },
  { id: "295", date: "21.10", names: ["Celina", "Urszula", "Elżbieta"] },
  { id: "296", date: "22.10", names: ["Filip", "Marek", "Józefina"] },
  { id: "297", date: "23.10", names: ["Jan", "Marlena", "Roman"] },
  { id: "298", date: "24.10", names: ["Marcin", "Rafał", "Antoni"] },
  { id: "299", date: "25.10", names: ["Daria", "Inga", "Katarzyna"] },
  { id: "300", date: "26.10", names: ["Damian", "Lucjan", "Lutosław"] },
  { id: "301", date: "27.10", names: ["Iwona", "Sabina", "Wincenty"] },
  { id: "302", date: "28.10", names: ["Szymon", "Tadeusz", "Cyryl"] },
  { id: "303", date: "29.10", names: ["Dalia", "Felicjan", "Franciszek"] },
  { id: "304", date: "30.10", names: ["Przemysław", "Zenobia", "Edmund"] },
  { id: "305", date: "31.10", names: ["Antonina", "Augusta", "Krzysztof"] },

  // LISTOPAD
  { id: "306", date: "01.11", names: ["Nikola", "Andrzej", "Konrad"] },
  { id: "307", date: "02.11", names: ["Bożydar", "Jerzy", "Małgorzata"] },
  { id: "308", date: "03.11", names: ["Hubert", "Sylwia", "Bogumił"] },
  { id: "309", date: "04.11", names: ["Jessica", "Helena", "Karol"] },
  { id: "310", date: "05.11", names: ["Sławomir", "Marek", "Zachariasz"] },
  { id: "311", date: "06.11", names: ["Anita", "Gabriela", "Krystyna"] },
  { id: "312", date: "07.11", names: ["Karina", "Longin"] },
  { id: "313", date: "08.11", names: ["Marcin", "Paweł", "Wiktoria"] },
  { id: "314", date: "09.11", names: ["Elżbieta", "Genowefa", "Ursyn"] },
  { id: "315", date: "10.11", names: ["Lena", "Andrzej", "Leon"] },
  { id: "316", date: "11.11", names: ["Marcin", "Alicja", "Bartłomiej"] },
  { id: "317", date: "12.11", names: ["Marcin", "Renata", "Witold"] },
  { id: "318", date: "13.11", names: ["Stanisław", "Stanisława", "Arkadia"] },
  { id: "319", date: "14.11", names: ["Agata", "Damian", "Elżbieta"] },
  { id: "320", date: "15.11", names: ["Albert", "Artur", "Leopold"] },
  { id: "321", date: "16.11", names: ["Agnieszka", "Edmund", "Małgorzata"] },
  { id: "322", date: "17.11", names: ["Elżbieta", "Grzegorz", "Wiktoria"] },
  { id: "323", date: "18.11", names: ["Aniela", "Karolina", "Gabriela"] },
  { id: "324", date: "19.11", names: ["Elżbieta", "Barbara", "Paweł"] },
  { id: "325", date: "20.11", names: ["Anatol", "Feliks", "Grzegorz"] },
  { id: "326", date: "21.11", names: ["Janusz", "Elwira", "Miriam"] },
  { id: "327", date: "22.11", names: ["Cecylia", "Marek", "Ernestyna"] },
  { id: "328", date: "23.11", names: ["Adela", "Felicyta", "Grzegorz"] },
  { id: "329", date: "24.11", names: ["Agnieszka", "Emilia", "Flora"] },
  { id: "330", date: "25.11", names: ["Katarzyna", "Elżbieta", "Erazm"] },
  { id: "331", date: "26.11", names: ["Konrad", "Sylwester", "Marcel"] },
  { id: "332", date: "27.11", names: ["Dominik", "Walery", "Wirgiliusz"] },
  { id: "333", date: "28.11", names: ["Jakub", "Zdzisław", "Grzegorz"] },
  { id: "334", date: "29.11", names: ["Błażej", "Walter", "Filomena"] },
  { id: "335", date: "30.11", names: ["Andrzej", "Fryderyk", "Justyna"] },

  // GRUDZIEŃ
  { id: "336", date: "01.12", names: ["Natalia", "Blanka", "Edmund"] },
  { id: "337", date: "02.12", names: ["Paulina", "Balbina", "Bibiana"] },
  { id: "338", date: "03.12", names: ["Franciszek", "Ksawery", "Kasjan"] },
  { id: "339", date: "04.12", names: ["Barbara", "Bernard", "Filip"] },
  { id: "340", date: "05.12", names: ["Bartosz", "Krystyna", "Anastazy"] },
  { id: "341", date: "06.12", names: ["Mikołaj", "Angelika", "Emilian"] },
  { id: "342", date: "07.12", names: ["Ambroży", "Marcin", "Urban"] },
  { id: "343", date: "08.12", names: ["Edyta", "Maria", "Alojzy"] },
  { id: "344", date: "09.12", names: ["Wiesław", "Leokadia", "Joachim"] },
  { id: "345", date: "10.12", names: ["Brajan", "Andrzej", "Daniel"] },
  { id: "346", date: "11.12", names: ["Artur", "Damazy", "Stefan"] },
  { id: "347", date: "12.12", names: ["Aleksander", "Dagmara", "Bartosz"] },
  { id: "348", date: "13.12", names: ["Łucja", "Otylia", "Walenty"] },
  { id: "349", date: "14.12", names: ["Alfred", "Dora", "Izydor"] },
  { id: "350", date: "15.12", names: ["Walerian", "Euzebiusz", "Teodor"] },
  { id: "351", date: "16.12", names: ["Albina", "Alicja", "Zdzisław"] },
  { id: "352", date: "17.12", names: ["Jolanta", "Łukasz", "Olimpia"] },
  { id: "353", date: "18.12", names: ["Bogusław", "Gracjan", "Zofia"] },
  { id: "354", date: "19.12", names: ["Dariusz", "Grzegorz", "Beniamin"] },
  { id: "355", date: "20.12", names: ["Bogumiła", "Dagmara", "Dominik"] },
  { id: "356", date: "21.12", names: ["Tomasz"] },
  { id: "357", date: "22.12", names: ["Franciszka", "Honorata", "Zenon"] },
  { id: "358", date: "23.12", names: ["Wiktoria", "Sławomir", "Anatola"] },
  { id: "359", date: "24.12", names: ["Adam", "Ewa", "Ewelina"] },
  { id: "360", date: "25.12", names: ["Natan", "Eugenia", "Maria"] },
  { id: "361", date: "26.12", names: ["Dionizy", "Szczepan", "Teodor"] },
  { id: "362", date: "27.12", names: ["Jan", "Żaneta", "Bartłomiej"] },
  { id: "363", date: "28.12", names: ["Antoni", "Emma", "Teofila"] },
  { id: "364", date: "29.12", names: ["Dawid", "Dominik", "Jonatan"] },
  { id: "365", date: "30.12", names: ["Eugeniusz", "Irmina", "Katarzyna"] },
  { id: "366", date: "31.12", names: ["Sylwester", "Melania", "Paulina"] },
];
